# Generated by Django 5.0.1 on 2024-01-04 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0002_event_description_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 1, 33, 63587, tzinfo=datetime.timezone.utc)),
        ),
    ]
