# Generated by Django 5.0.1 on 2024-01-04 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0004_remove_task_notification_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 39, 19, 927813, tzinfo=datetime.timezone.utc)),
        ),
    ]
