# Generated by Django 5.0.1 on 2024-01-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0014_alter_event_end_date_alter_project_reminder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 14, 12, 39, 378552, tzinfo=datetime.timezone.utc)),
        ),
    ]
