# Generated by Django 5.0.1 on 2024-01-06 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCalendar', '0016_project_reminder_displayed_alter_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='reminder_displayed',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 17, 14, 4, 923178, tzinfo=datetime.timezone.utc)),
        ),
    ]
